"""Code generator for converting visual sequences to Python code."""

from typing import List
from gui.models.sequence_step import SequenceStep, PulseStep, DelayStep, LoopStep, StepType


class SequenceCodeGenerator:
    """Generates Python code from visual pulse sequences."""
    
    @staticmethod
    def generate_code(steps: List[SequenceStep], exp_type: str = "1D") -> str:
        """
        Generate executable Python code from sequence steps.
        
        Args:
            steps: List of sequence steps
            exp_type: "1D" or "2D"
            
        Returns:
            Complete Python script as string
        """
        # Check if this is actually a 2D experiment
        has_sweep = any(isinstance(s, PulseStep) and s.amplitude_sweep for s in steps)
        if has_sweep:
            exp_type = "2D"
        
        # Generate header
        code = SequenceCodeGenerator._generate_header(exp_type)
        
        # Generate experiment initialization
        code += SequenceCodeGenerator._generate_experiment_init(exp_type, steps)
        
        # Generate pulse sequence
        code += SequenceCodeGenerator._generate_sequence(steps, exp_type)
        
        # Generate footer (execution note)
        code += SequenceCodeGenerator._generate_footer()
        
        return code
    
    @staticmethod
    def _generate_header(exp_type: str) -> str:
        """Generate script header with imports."""
        return '''"""
Pulse sequence generated by GUI Sequence Builder
"""

import qeg_nmr_qua as qnmr
from qualang_tools.units import unit
from pathlib import Path
import numpy as np

u = unit(coerce_to_integer=True)

# Load active settings from GUI
settings = qnmr.ExperimentSettings.from_json("active-settings.json")

# Generate configuration from settings
cfg = qnmr.cfg_from_settings(settings)

'''
    
    @staticmethod
    def _generate_experiment_init(exp_type: str, steps: List[SequenceStep]) -> str:
        """Generate experiment initialization code."""
        if exp_type == "2D":
            # Find sweep parameters
            sweep_step = next((s for s in steps if isinstance(s, PulseStep) and s.amplitude_sweep), None)
            if sweep_step:
                code = f"""# Define sweep parameters
sweep_values = np.linspace({sweep_step.sweep_start}, {sweep_step.sweep_end}, {sweep_step.sweep_points})

# Create 2D experiment
expt = qnmr.Experiment2D(
    config=cfg,
    settings=settings,
)

"""
            else:
                code = """# Create 2D experiment
expt = qnmr.Experiment2D(
    config=cfg,
    settings=settings,
)

"""
        else:
            code = """# Create 1D experiment
expt = qnmr.Experiment1D(
    config=cfg,
    settings=settings,
)

"""
        
        return code
    
    @staticmethod
    def _generate_sequence(steps: List[SequenceStep], exp_type: str) -> str:
        """Generate pulse sequence code."""
        code = "# Build pulse sequence\n"
        
        for step in steps:
            code += SequenceCodeGenerator._generate_step(step, exp_type)
        
        return code + "\n"
    
    @staticmethod
    def _generate_step(step: SequenceStep, exp_type: str, indent: int = 0) -> str:
        """Generate code for a single step."""
        indent_str = "    " * indent
        
        if isinstance(step, PulseStep):
            return SequenceCodeGenerator._generate_pulse(step, exp_type, indent_str)
        elif isinstance(step, DelayStep):
            return SequenceCodeGenerator._generate_delay(step, indent_str)
        elif isinstance(step, LoopStep):
            return SequenceCodeGenerator._generate_loop(step, exp_type, indent_str)
        
        return ""
    
    @staticmethod
    def _generate_pulse(pulse: PulseStep, exp_type: str, indent: str) -> str:
        """Generate code for pulse step."""
        # Build pulse parameters
        params = []
        
        # Pulse name - use the actual pulse name string
        params.append(f'name="{pulse.pulse_name}"')
        
        # Element name
        params.append(f'element="{pulse.element}"')
        
        # Handle amplitude
        if pulse.amplitude_sweep:
            params.append("amplitude=sweep_values")
        elif pulse.amplitude is not None and pulse.amplitude != float('-inf'):
            params.append(f"amplitude={pulse.amplitude}")
        
        # Handle phase
        if pulse.phase is not None and pulse.phase != float('-inf'):
            params.append(f"phase={pulse.phase}")
        
        # Handle duration
        if pulse.duration is not None:
            params.append(f"duration={pulse.duration}")
        
        param_str = ", ".join(params)
        
        return f"{indent}expt.add_pulse({param_str})\n"
    
    @staticmethod
    def _generate_delay(delay: DelayStep, indent: str) -> str:
        """Generate code for delay step."""
        # Convert to microseconds for readability
        if delay.duration_ns >= 1000:
            duration_us = delay.duration_ns / 1000
            return f"{indent}expt.add_delay({duration_us} * u.us)\n"
        else:
            return f"{indent}expt.add_delay({delay.duration_ns})\n"
    
    @staticmethod
    def _generate_loop(loop: LoopStep, exp_type: str, indent: str) -> str:
        """Generate code for loop step."""
        code = f"{indent}# Loop: {loop.iterations} iterations\n"
        code += f"{indent}for _ in range({loop.iterations}):\n"
        
        for nested_step in loop.steps:
            code += SequenceCodeGenerator._generate_step(nested_step, exp_type, indent.count("    ") // 4 + 1)
        
        return code
    
    @staticmethod
    def _generate_footer() -> str:
        """Generate script footer."""
        return """# Note: Execute via GUI Run button, not directly in script
# expt.execute_experiment()
"""


def generate_code_from_sequence(steps: List[SequenceStep]) -> str:
    """
    Convenience function to generate code from sequence.
    
    Args:
        steps: List of sequence steps
        
    Returns:
        Complete Python script
    """
    return SequenceCodeGenerator.generate_code(steps)
