import qeg_nmr_qua as qnmr

from qualang_tools.units import unit
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from scipy.special import jn

u = unit(coerce_to_integer=True)

# create base settings object for experiments
settings = qnmr.ExperimentSettings(
    n_avg=4,
    pulse_length=1.14 * u.us,
    pulse_amplitude=0.48,  # amplitude is 0.5*Vpp
    pulse_shape="square",
    pulse_rise_fall=0.0,  # 0% rise/fall time
    rotation_angle=247.54,  # degrees
    thermal_reset=4 * u.s,
    center_freq=282.1901 * u.MHz,
    offset_freq=9125 * u.Hz,
    readout_delay=20 * u.us,
    dwell_time=4 * u.us,
    readout_start=0 * u.us,
    readout_end=256 * u.us,
    save_dir=Path.home() / "Dropbox/QEG/NMR/RawData" / Path(__file__).stem,
)


cfg = qnmr.cfg_from_settings(settings)

# sequence time constants
t0 = 5 * u.us
p1 = settings.pulse_length
thlf = (t0 - p1) / 2
t1 = t0 - p1
t2 = 2 * t0 - p1

# Pine-8 sequence pattern for engineering +/- DQ
pine8_phases = np.array([0, 0, 0, 0, 180, 180, 180, 180])
pine8_bwd_phases = np.array([90, 90, 90, 90, 270, 270, 270, 270])
pine8_delays = np.array([thlf, t2, t1, t2, t1, t2, t1, t2, thlf])

M = 10  # number of coherences
kick_angles = np.arange(0, 360, 180 / M)  # degrees, from 0 to 360 in steps of 180/M

# evolve for up to 24 periods, 0 to 24
period_list = np.arange(0, 25, 1)

# define experiment object
expt = qnmr.Experiment3D(settings=settings, config=cfg)

# measure Z coherences in generated by Z operator evolving under DQ

# rho0 = Z, evolve under DQ
expt.add_floquet_sequence(
    phases=pine8_phases, delays=pine8_delays, repetitions=period_list, loop_layer=1
)

# rotate rho(t) by variable angle about Z
expt.add_z_rotation(
    angle=kick_angles, elements=(settings.res_key, settings.helper_key), loop_layer=2
)

# reverse evolution via -DQ
expt.add_floquet_sequence(
    phases=pine8_bwd_phases, delays=pine8_delays, repetitions=period_list, loop_layer=1
)

# filter transients
expt.add_delay(1 * u.ms)

# measure Z
expt.add_pulse(element=settings.res_key)

expt.update_sweep_axis_inner(kick_angles)
expt.update_sweep_axis_outer(period_list)
expt.update_sweep_label_inner("Interior Z Rotation Angle (degrees)")
expt.update_sweep_label_outer("Floquet Periods")
expt.execute_experiment()
# expt.remove_initial_delay()
# expt.simulate_experiment()
