from ast import operator

import qeg_nmr_qua as qnmr

import json
from pathlib import Path
from qualang_tools.units import unit
import matplotlib.pyplot as plt
import numpy as np
from scipy.optimize import curve_fit
from scipy.special import jn

u = unit(coerce_to_integer=True)

# create base settings object for experiments
settings = qnmr.ExperimentSettings(
    n_avg=4,
    pulse_length=1.1 * u.us,
    pulse_amplitude=0.48,  # amplitude is 0.5*Vpp
    pulse_shape="square",
    pulse_rise_fall=0.0,  # 0% rise/fall time
    rotation_angle=247.54,  # degrees
    thermal_reset=4 * u.s,
    center_freq=282.1901 * u.MHz,
    offset_freq=9250 * u.Hz,
    readout_delay=20 * u.us,
    dwell_time=4 * u.us,
    readout_start=0 * u.us,
    readout_end=256 * u.us,
    save_dir=Path.home() / "Dropbox/QEG/NMR/RawData" / Path(__file__).stem,
)

cfg = qnmr.cfg_from_settings(settings)

execute = True  # whether to execute a new experiment or load from previous JSON file
if not execute:
    data_path = settings.save_dir / "experiment_0005/data.json"

rho0 = "Z"  # evolve either X,Y,Z operator under DQ (& measure corresponding observable)
mqc_plot = True  # whether to plot MQC intensities at the end
remove_echo_decay = True  # For observing operator spreading |Cₘ(t)|² / Σₘ|Cₘ(t)|²

# sequence time constants
t0 = 5 * u.us
p1 = settings.pulse_length
thlf = (t0 - p1) / 2
t1 = t0 - p1
t2 = 2 * t0 - p1

# Pine-8 sequence pattern for engineering +/- DQ
pine8_phases = np.array([0, 0, 0, 0, 180, 180, 180, 180])
pine8_bwd_phases = np.array([90, 90, 90, 90, 270, 270, 270, 270])
pine8_delays = np.array([thlf, t2, t1, t2, t1, t2, t1, t2, thlf])

M = 10  # number of coherences
kick_angles = np.arange(0, 360, 180 / M)  # degrees, from 0 to 360 in steps of 180/M

# evolve for up to 24 periods, 0 to 24
period_list = np.arange(0, 25, 1)

# define experiment object
expt = qnmr.Experiment3D(settings=settings, config=cfg)

# measure Z coherences in generated by operator evolving under DQ

# rotate to evolve X, Y, or Z state operator under DQ
if rho0 == "X":
    expt.add_pulse(
        phase=90, element=settings.res_key, phase=[90, 270], phase_cycle=True
    )
elif rho0 == "Y":
    expt.add_pulse(phase=0, element=settings.res_key, phase=[180, 0], phase_cycle=True)
elif rho0 == "Z":
    pass
else:
    raise ValueError("Invalid operator choice. Must be 'X', 'Y', or 'Z'.")
expt.add_delay(2.5 * u.us)

# rho0 = Z, evolve under DQ
expt.add_floquet_sequence(
    phases=pine8_phases, delays=pine8_delays, repetitions=period_list, loop_layer=1
)

# rotate rho(t) by variable angle about Z
expt.add_z_rotation(
    angle=kick_angles, elements=(settings.res_key, settings.helper_key), loop_layer=2
)

# reverse evolution via -DQ
expt.add_floquet_sequence(
    phases=pine8_bwd_phases, delays=pine8_delays, repetitions=period_list, loop_layer=1
)

# rotate back to measure X, Y, or Z observable
expt.add_delay(2.5 * u.us)
if rho0 == "X":
    expt.add_pulse(phase=[270, 90], phase_cycle=True, element=settings.res_key)
elif rho0 == "Y":
    expt.add_pulse(phase=[0, 180], phase_cycle=True, element=settings.res_key)
elif rho0 == "Z":
    pass
else:
    raise ValueError("Invalid operator choice. Must be 'X', 'Y', or 'Z'.")

# filter transients and measure
expt.add_delay(1 * u.ms)

expt.add_pulse(element=settings.res_key, phase=[90, 270], phase_cycle=True)

expt.add_measurement(
    phase=[0, 180],
    probe_element=settings.res_key,
    helper_element=settings.helper_key,
    phase_cycle=True,
)

expt.update_sweep_axis_inner(kick_angles)
expt.update_sweep_axis_outer(period_list)
expt.update_sweep_label_inner("Interior Z Rotation Angle (degrees)")
expt.update_sweep_label_outer("Floquet Periods")

if execute:
    expt.execute_experiment()
    # expt.remove_initial_delay()
    # expt.simulate_experiment()

if mqc_plot:

    if execute:
        data_dict = expt.save_data_dict
    else:
        # Load JSON file from a previous experiment if not executing current one
        with open(data_path, "r") as f:
            data_dict = json.load(f)

    re = np.array(data_dict["I_data"]) * 1e6
    periods = np.array(data_dict["sweep_axis_outer"])
    rotation_deg = np.array(data_dict["sweep_axis_inner"])
    re = re[:, :, 0]  # Plot first point of FID for each period & rotation
    n_periods, n_phi = re.shape

    if remove_echo_decay:
        signal = (
            re / re[:, 0][:, np.newaxis]
        )  # normalize to φ=0 to remove echo decay envelope and observe operator spreading
    else:
        signal = (
            re / re[0, 0]
        )  # preserve echo decay envelope, observe MQC intensities more quantitatively

    # FFT over φ to extract MQC intensities
    rotation_rad = np.deg2rad(rotation_deg)
    dphi = np.mean(np.diff(rotation_rad))
    mqc = np.fft.fft(signal, axis=1) / n_phi
    mqc = np.fft.fftshift(mqc, axes=1)
    mqc_intensity = np.abs(mqc)
    coherence_orders = np.fft.fftshift(
        np.fft.fftfreq(n_phi, d=dphi / (2 * np.pi))
    )  # Frequency axis (coherence order)

    # 3D Plot
    fig = plt.figure()
    ax = fig.add_subplot(111, projection="3d")

    # render MQC intensity of each order back to front
    sort_idx = np.argsort(coherence_orders)[::-1]
    for j in sort_idx:
        threshold = 0.025  # gray out low intensity coherences
        if np.average(mqc_intensity[:, j]) < threshold:
            color = "darkgray"
        else:
            color = None

        ax.plot(
            periods,
            np.full_like(periods, coherence_orders[j]),
            mqc_intensity[:, j],
            color=color,
        )

    ax.set_xlabel("Floquet Periods")
    ax.set_xlim(0, periods.max())
    ax.set_ylabel("Coherence Order")
    ax.set_yticks(np.arange(coherence_orders.min(), coherence_orders.max(), step=2))
    ax.set_zlabel("MQC Intensity")
    ax.set_zlim(0, mqc_intensity.max())

    plt.title(
        "MQC Intensities" + (" (Normalized Echo Decay)" if remove_echo_decay else "")
    )
    plt.tight_layout()
    plt.show()
